alter table TASKS_TASK add constraint FK_TASKS_TASK_ON_TASK_TYPICAL foreign key (TASK_TYPICAL_ID) references TASKS_TASK_TYPICAL(ID);
create index IDX_TASKS_TASK_ON_TASK_TYPICAL on TASKS_TASK (TASK_TYPICAL_ID);
